//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinaShoseShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donhang
    {
        public int Madon { get; set; }
        public System.DateTime Ngaydat { get; set; }
        public Nullable<int> Tinhtrang { get; set; }
        public Nullable<int> Manguoidung { get; set; }
        public string TenSanPham { get; set; }
        public decimal GiaTien { get; set; }
        public int SoLuong { get; set; }
        public string Size { get; set; }
        public string TenNguoiDat { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
    
        public virtual Nguoidung Nguoidung { get; set; }
    }
}
